title = "Across the Causeway Transit Riders Collective"
baseURL = "https://acrossthecauseway.com"
languageCode = "en-us"
theme = "ananke"
themesDir = "themes"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2

[menu]
  [[menu.main]]
    identifier = "fact_checking"
    name = "Fact-checking UCD"
    pre = "test_pre"
    url = "/#fact-checking"
[[menu.main]]
  identifier = "voice_concerns"
  name = "Voice Your Concerns"
  pre = "test_pre"
  url = "/#voice-your-concerns"
[[menu.main]]
  identifier = "letter"
  name = "Riders' Letter"
  pre = "test_pre"
  url = "/#letter"
